---
title: "About Me"
---

Hi! I’m Clara, a Master's student in Applied Economics and Data Science at the University of Pennsylvania. Before coming to Penn, I studied Japanese and Financial Engineering at Nanjing University and spent a semester as an exchange student at the University of Tokyo.

I’m interested in econometrics, financial economics, and data analysis. I have experience working with R, Python and SQL, and I enjoy using data to better understand real-world problems.

In the future, I hope to build a career where I can combine my background in economics and finance with data science and quantitative analysis.

## Education

-   Master of Applied Economics and Data Science, University of Pennsylvania (expected 2027)
-   B.A. in Japanese; Minor in Financial Engineering, Nanjing University 2026
-   Exchange Student, The University of Tokyo 2024

## Interests

-   Econometrics
-   Data Analysis
-   Financial Economics

## Contact

## jiayinxu\@sas.upenn.edu

------------------------------------------------------------------------
